### ISSUE TITLE
Add option to delete blobs before upload

### ISSUE THREAD

**Issue by ppegusii** [duizendnegen/ember-cli-deploy-azure-blob#12]
Some files may be fingerprinted for cache busting, causing the container to grow with each deployment. Add option to delete all blobs in the container before upload.

**Comment by duizendnegen** [comment]
I'm not in favour of this issue / solution, storage space is cheap, being able to roll back to earlier versions is essential for Ember CLI Deploy. Closing, feel free to re-open if this merits a further discussion.
