### ISSUE TITLE
Uploads to blob container with folder structure that breaks links in index.html

### ISSUE THREAD

**Issue by mattmazzola** [duizendnegen/ember-cli-deploy-azure-blob#8]
```
ember-cli: 2.9.1
node: 6.3.1
os: win32 x64
```

I set up the environment config and am able to deploy successfully, but the resulting files do not look correct in the blob container.

I expected them to mimic what would be in the dist folder, but they upload like this:

```
/containerName/assets/sc2-api-client-7fced5182c329ff763a6d603d94f9a0a.js
/containerName/assets/sc2-api-client-970a719dd00d900e61c4bbd28147cce6.css
/containerName/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css
/containerName/assets/vendor-fa87c36942e1df313e79610b037c0461.js
/containerName/tmp/deploy-dist/crossdomain.xml
/containerName/tmp/deploy-dist/index.html
/containerName/tmp/deploy-dist/robots.txt
```

1. I expected the index, crossdomain, and robots to also be fingerprinted so the unique version of index points it's own unique files. (From what it looks like now, each upload would overwrite the older index files which means I can't have multiple revisions up there simultaneously)

2. I expected index, crossdomain, and robots files to be at the root of the container instead of in `tmp/deploy-dist`

3. The links inside the `index.html` use relative paths from the root such as `/assets/vendor-fa87c36942e1df313e79610b037c0461.js` which does not take into account the `/containerName` portion of the url so even if I manually move them from the `tmp/deploy-dist` to the root it will still not work.

Is there some extra plugin i'm missing or configuration step?
I just followed the instructions from the readme and not sure what else there is to configure.

**Comment by mattmazzola** [comment]
I realized I had not setup the fingerprint prepend url and that was why the links were still using relative paths.

I submitted #9 to hopefully make this clearer for other people in the future.

**Comment by duizendnegen** [comment]
Hi @mattmazzola - yes, Azure Blob does something similar to AWS S3, but with a slight difference: it is just meant to upload the assets (images, Javascript, CSS) and importantly *not* different revisions of `index.html`, the 'bootstrap' page that points to different assets. It's essentially the difference of `ember-cli-deploy-s3` and `ember-cli-deploy-s3-index` in the context of S3.

In my deployment set-up I have `ember-cli-deploy-azure-tables` responsible for storing items in the Azure Table Storage (a key/value storage like Redis). What would be possible is to open a new repository (called `ember-cli-deploy-azure-blob-index` or similar) and follow the strategy there that `ember-cli-deploy-s3-index` takes for deploying these bootstrap pages.

**Comment by mattmazzola** [comment]
Oh I see. So if I understand, the addon is operating as designed and not intended to upload multiple revisions of the index page.
I will check out those other libraries and take a look at building the one for the index pages. Thanks.
